# Generated by Django 3.1.1 on 2020-09-13 20:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city', models.TextField(blank=True, choices=[('Amman', 'Amman'), ('Irbid', 'Irbid')], null=True)),
                ('detailed_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
