# Generated by Django 3.1.1 on 2020-09-13 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('shipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shipments',
            field=models.ManyToManyField(related_name='related_clients', to='shipment.Shipment'),
        ),
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
