version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3308:3308'
    volumes:
      - "./db:/var/lib/mysql"
    environment:
       MYSQL_DATABASE: 'delivery_db'
       MYSQL_ROOT_PASSWORD: 'QWEqwe!1'
       USER: 'root'
       HOST: '127.0.0.1'
  web:
    build: /
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db