# Generated by Django 3.1.1 on 2020-09-14 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
        migrations.AddField(
            model_name='shipment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('dropped', 'dropped'), ('picked up', 'picked up')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='size',
            field=models.TextField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credentials.credentials'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
