# Generated by Django 3.1.1 on 2020-09-16 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200914_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('in process', 'in process'), ('dropped', 'dropped'), ('picked up', 'picked up')], default='draft', max_length=10),
        ),
    ]
