# Generated by Django 3.1.1 on 2020-09-13 20:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('drop_off_cred', models.TextField()),
                ('pickup_cred', models.TextField()),
                ('valid_drop', models.BooleanField(default=False)),
                ('valid_pickup', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
